import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, readFile, realpath, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { makeTempDir, readRegistry, runRepoCli } from "./test-helpers.mjs";

test("list-platforms is stable and tiered", async () => {
  const { stdout } = await runRepoCli(["list-platforms"]);
  const lines = stdout.trim().split("\n");

  assert.equal(lines[0], "host\ttier\tartifacts\tdescription");
  assert.equal(lines[1], "claude\tverified\tskill,command\tClaude Code");
  assert.equal(lines.at(-1), "antigravity\texperimental\tskill\tAntigravity staged skill pack");
});

test("version flags print package version", async () => {
  const packageJson = JSON.parse(
    await readFile(join(process.cwd(), "package.json"), "utf8"),
  );

  const versionFlag = await runRepoCli(["--version"]);
  const versionCommand = await runRepoCli(["version"]);

  assert.equal(versionFlag.stdout.trim(), packageJson.version);
  assert.equal(versionCommand.stdout.trim(), packageJson.version);
});

test("verified local install writes managed Codex skill from cwd with --ai/--ada and updates registry", async () => {
  const target = await makeTempDir("code-mux-local-");
  const fakeHome = await makeTempDir("code-mux-home-");

  await runRepoCli(
    [
      "init",
      "--ai",
      "codex",
      "--ada",
      "gemini",
    ],
    {
      cwd: target,
      env: { HOME: fakeHome },
    },
  );

  const output = join(target, ".codex", "skills", "mux-gemini", "SKILL.md");
  const content = await readFile(output, "utf8");
  const registry = await readRegistry(fakeHome);

  assert.match(content, /generated-by: code-mux/);
  assert.match(content, /Host: `codex`/);
  assert.match(content, /Generated by `code-mux` v\d+\.\d+\.\d+/);
  assert.match(content, /gemini-oriented long-context exploration/i);
  assert.equal(registry.entries.length, 1);
  assert.equal(registry.entries[0].scope, "local");
  assert.equal(registry.entries[0].targetRoot, await realpath(target));
  assert.equal(registry.entries[0].host, "codex");
  assert.equal(registry.entries[0].adapter, "gemini");
});

test("legacy --host/--adapter/--target flags remain compatible", async () => {
  const target = await makeTempDir("code-mux-legacy-");
  const fakeHome = await makeTempDir("code-mux-home-");

  await runRepoCli([
    "init",
    "--host",
    "codex",
    "--artifact",
    "skill",
    "--adapter",
    "kimi",
    "--target",
    target,
  ], {
    env: { HOME: fakeHome },
  });

  const output = join(target, ".codex", "skills", "mux-kimi", "SKILL.md");
  const content = await readFile(output, "utf8");
  const registry = await readRegistry(fakeHome);

  assert.match(content, /generated-by: code-mux/);
  assert.match(content, /Host: `codex`/);
  assert.equal(registry.entries.length, 1);
  assert.equal(registry.entries[0].artifact, "skill");
});

test("global install resolves into HOME rather than cwd", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const workspace = await makeTempDir("code-mux-work-");

  await runRepoCli(
    [
      "init",
      "--ai",
      "claude",
      "--artifact",
      "command",
      "--ada",
      "kimi",
      "--global",
    ],
    {
      cwd: workspace,
      env: { HOME: fakeHome },
    },
  );

  const output = join(fakeHome, ".claude", "commands", "code-mux", "kimi.md");
  const content = await readFile(output, "utf8");
  const registry = await readRegistry(fakeHome);

  assert.match(content, /Host: `claude`/);
  await assert.rejects(readFile(join(workspace, ".claude", "commands", "code-mux", "kimi.md")));
  assert.equal(registry.entries.length, 1);
  assert.equal(registry.entries[0].scope, "global");
  assert.equal(registry.entries[0].targetRoot, fakeHome);
});

test("experimental host requires explicit opt-in", async () => {
  const target = await makeTempDir("code-mux-exp-");
  const fakeHome = await makeTempDir("code-mux-home-");

  await assert.rejects(
    runRepoCli([
      "init",
      "--host",
      "kimi",
      "--artifact",
      "memory-pack",
      "--adapter",
      "gemini",
      "--target",
      target,
    ], {
      env: { HOME: fakeHome },
    }),
  );

  await runRepoCli([
    "init",
    "--host",
    "kimi",
    "--artifact",
    "memory-pack",
    "--adapter",
    "gemini",
    "--target",
    target,
    "--include-experimental",
  ], {
    env: { HOME: fakeHome },
  });

  const output = join(
    target,
    ".code-mux",
    "experimental",
    "kimi",
    "mux-gemini",
    "AGENTS.md",
  );
  const content = await readFile(output, "utf8");
  assert.match(content, /Experimental/);
});

test("unmanaged files fail unless force is provided", async () => {
  const target = await makeTempDir("code-mux-force-");
  const fakeHome = await makeTempDir("code-mux-home-");
  const output = join(target, ".codex", "skills", "mux-kimi", "SKILL.md");

  await mkdir(join(target, ".codex", "skills", "mux-kimi"), { recursive: true });
  await writeFile(output, "# local edit\n", "utf8");

  await assert.rejects(
    runRepoCli([
      "init",
      "--host",
      "codex",
      "--artifact",
      "skill",
      "--adapter",
      "kimi",
      "--target",
      target,
    ], {
      env: { HOME: fakeHome },
    }),
  );

  await runRepoCli([
    "init",
    "--host",
    "codex",
    "--artifact",
    "skill",
    "--adapter",
    "kimi",
    "--target",
    target,
    "--force",
  ], {
    env: { HOME: fakeHome },
  });

  const content = await readFile(output, "utf8");
  assert.match(content, /generated-by: code-mux/);
});

test("host all writes verified outputs only by default", async () => {
  const target = await makeTempDir("code-mux-all-");
  const fakeHome = await makeTempDir("code-mux-home-");

  await runRepoCli([
    "init",
    "--host",
    "all",
    "--target",
    target,
  ], {
    env: { HOME: fakeHome },
  });

  const claudeSkill = join(target, ".claude", "skills", "mux-kimi", "SKILL.md");
  const qoderCommand = join(target, ".qoder", "commands", "mux-gemini.md");
  const codexSkill = join(target, ".codex", "skills", "mux-antigravity", "SKILL.md");
  const stagedKimi = join(target, ".code-mux", "experimental", "kimi", "mux-kimi", "AGENTS.md");

  assert.ok(await readFile(claudeSkill, "utf8"));
  assert.ok(await readFile(qoderCommand, "utf8"));
  assert.ok(await readFile(codexSkill, "utf8"));
  await assert.rejects(readFile(stagedKimi, "utf8"));
});

test("re-running init for the same footprint updates the registry idempotently", async () => {
  const target = await makeTempDir("code-mux-idempotent-");
  const fakeHome = await makeTempDir("code-mux-home-");

  await runRepoCli(["init", "--ai", "codex", "--ada", "kimi"], {
    cwd: target,
    env: { HOME: fakeHome },
  });
  const firstRegistry = await readRegistry(fakeHome);

  await runRepoCli(["init", "--ai", "codex", "--ada", "kimi"], {
    cwd: target,
    env: { HOME: fakeHome },
  });
  const secondRegistry = await readRegistry(fakeHome);

  assert.equal(firstRegistry.entries.length, 1);
  assert.equal(secondRegistry.entries.length, 1);
  assert.equal(firstRegistry.entries[0].entryId, secondRegistry.entries[0].entryId);
});

test("local and global installs for the same selectors coexist in the registry", async () => {
  const target = await makeTempDir("code-mux-coexist-");
  const fakeHome = await makeTempDir("code-mux-home-");

  await runRepoCli(["init", "--ai", "codex", "--ada", "kimi"], {
    cwd: target,
    env: { HOME: fakeHome },
  });
  await runRepoCli(["init", "--ai", "codex", "--ada", "kimi", "--global"], {
    cwd: target,
    env: { HOME: fakeHome },
  });

  const registry = await readRegistry(fakeHome);
  assert.equal(registry.entries.length, 2);
  assert.deepEqual(
    registry.entries.map((entry) => entry.scope).sort(),
    ["global", "local"],
  );
});
