import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  createGlobalInstalledCli,
  createLocalInstalledCli,
  createNpmStub,
  makeTempDir,
  readJsonLines,
  readRegistry,
  runInstalledCli,
  runRepoCli,
} from "./test-helpers.mjs";

test("help output documents update and repair commands", async () => {
  const { stdout } = await runRepoCli(["help"]);
  assert.match(stdout, /code-mux update/);
  assert.match(stdout, /code-mux relink <entry-id> <new-path>/);
  assert.match(stdout, /code-mux forget <entry-id>/);
});

test("source-checkout update is rejected with manual instructions", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");

  await assert.rejects(
    runRepoCli(["update"], { env: { HOME: fakeHome } }),
    /does not support source-checkout execution/i,
  );
});

test("supported local npm install self-updates and refreshes with a single re-exec", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const { projectRoot, entryPath } = await createLocalInstalledCli();
  const npmStub = await createNpmStub();
  const phaseLog = join(await makeTempDir("code-mux-phase-log-"), "phase.ndjson");
  const npmLog = join(await makeTempDir("code-mux-npm-log-"), "npm.ndjson");
  const stateRoot = await makeTempDir("code-mux-state-");

  await runInstalledCli(entryPath, ["init", "--ai", "codex", "--ada", "kimi"], {
    cwd: projectRoot,
    env: { HOME: fakeHome },
  });

  const generatedFile = join(projectRoot, ".codex", "skills", "mux-kimi", "SKILL.md");
  const baseline = await readFile(generatedFile, "utf8");
  await writeFile(generatedFile, baseline.replace("Host: `codex`", "Host: `stale-codex`"), "utf8");

  const { stdout } = await runInstalledCli(entryPath, ["update"], {
    cwd: projectRoot,
    env: {
      HOME: fakeHome,
      CODE_MUX_NPM_BIN: npmStub,
      CODE_MUX_TEST_NEW_VERSION: "9.9.9",
      CODE_MUX_TEST_PHASE_LOG: phaseLog,
      CODE_MUX_TEST_NPM_LOG: npmLog,
      CODE_MUX_TEST_STATE_DIR: stateRoot,
    },
  });

  const content = await readFile(generatedFile, "utf8");
  const phaseEvents = await readJsonLines(phaseLog);
  const npmEvents = await readJsonLines(npmLog);
  const registry = await readRegistry(fakeHome);

  assert.match(stdout, /^phase\trefresh/m);
  assert.match(stdout, /^code-mux-version\t9\.9\.9$/m);
  assert.match(content, /Host: `codex`/);
  assert.match(content, /Generated by `code-mux` v9\.9\.9/);
  assert.deepEqual(
    phaseEvents.map((entry) => entry.event),
    [
      "self-update:start",
      "self-update:complete",
      "refresh:start",
      "refresh:complete",
      "refresh:cleanup",
    ],
  );
  assert.equal(npmEvents.length, 1);
  assert.deepEqual(npmEvents[0].argv, [
    "install",
    "--no-save",
    "--ignore-scripts",
    "@moonraing7/code-mux-plugin@latest",
  ]);
  assert.equal(registry.entries.length, 1);
  assert.equal(registry.entries[0].packageVersion, "9.9.9");
  assert.deepEqual(await readdir(stateRoot), []);
});

test("supported global npm install self-updates and refreshes home-scoped outputs", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const workspace = await makeTempDir("code-mux-work-");
  const { entryPath } = await createGlobalInstalledCli();
  const npmStub = await createNpmStub();
  const npmLog = join(await makeTempDir("code-mux-npm-log-"), "npm.ndjson");

  await runInstalledCli(entryPath, [
    "init",
    "--ai",
    "claude",
    "--artifact",
    "command",
    "--ada",
    "kimi",
    "--global",
  ], {
    cwd: workspace,
    env: { HOME: fakeHome },
  });

  const generatedFile = join(fakeHome, ".claude", "commands", "code-mux", "kimi.md");
  const { stdout } = await runInstalledCli(entryPath, ["update"], {
    cwd: workspace,
    env: {
      HOME: fakeHome,
      CODE_MUX_NPM_BIN: npmStub,
      CODE_MUX_TEST_NEW_VERSION: "8.8.8",
      CODE_MUX_TEST_NPM_LOG: npmLog,
    },
  });

  const content = await readFile(generatedFile, "utf8");
  const npmEvents = await readJsonLines(npmLog);

  assert.match(stdout, /^code-mux-version\t8\.8\.8$/m);
  assert.match(content, /Generated by `code-mux` v8\.8\.8/);
  assert.deepEqual(npmEvents[0].argv, [
    "install",
    "--global",
    "--ignore-scripts",
    "@moonraing7/code-mux-plugin@latest",
  ]);
});

test("npm exec and bun launchers are rejected", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const { projectRoot, entryPath } = await createLocalInstalledCli();
  const blockedNpmBin = join(fakeHome, "blocked-npm");

  await assert.rejects(
    runInstalledCli(entryPath, ["update"], {
      cwd: projectRoot,
      env: {
        HOME: fakeHome,
        CODE_MUX_NPM_BIN: blockedNpmBin,
        npm_command: "exec",
      },
    }),
    /does not support npm exec or npx/i,
  );

  await assert.rejects(
    runInstalledCli(entryPath, ["update"], {
      cwd: projectRoot,
      env: {
        HOME: fakeHome,
        CODE_MUX_NPM_BIN: blockedNpmBin,
        npm_config_user_agent: "bun/1.1.0",
      },
    }),
    /does not support bun-based launchers/i,
  );
});

test("failed self-update cleans the refresh marker state", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const stateRoot = await makeTempDir("code-mux-state-");
  const { projectRoot, entryPath } = await createLocalInstalledCli();

  await runInstalledCli(entryPath, ["init", "--ai", "codex", "--ada", "kimi"], {
    cwd: projectRoot,
    env: { HOME: fakeHome },
  });

  await assert.rejects(
    runInstalledCli(entryPath, ["update"], {
      cwd: projectRoot,
      env: {
        HOME: fakeHome,
        CODE_MUX_NPM_BIN: join(fakeHome, "missing-npm"),
        CODE_MUX_TEST_STATE_DIR: stateRoot,
      },
    }),
  );

  assert.deepEqual(await readdir(stateRoot), []);
});

test("stale entries do not block healthy refreshes and can be forgotten", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const { projectRoot, entryPath } = await createLocalInstalledCli();
  const npmStub = await createNpmStub();
  const staleTarget = await makeTempDir("code-mux-stale-target-");

  await runInstalledCli(entryPath, ["init", "--ai", "codex", "--ada", "kimi"], {
    cwd: projectRoot,
    env: { HOME: fakeHome },
  });
  await runInstalledCli(entryPath, [
    "init",
    "--ai",
    "claude",
    "--artifact",
    "command",
    "--ada",
    "kimi",
    "--target",
    staleTarget,
  ], {
    cwd: projectRoot,
    env: { HOME: fakeHome },
  });

  const registryBefore = await readRegistry(fakeHome);
  const staleEntry = registryBefore.entries.find((entry) => entry.targetRoot === staleTarget);
  assert.ok(staleEntry);

  await rm(staleTarget, { recursive: true, force: true });

  const { stdout } = await runInstalledCli(entryPath, ["update"], {
    cwd: projectRoot,
    env: {
      HOME: fakeHome,
      CODE_MUX_NPM_BIN: npmStub,
      CODE_MUX_TEST_NEW_VERSION: "7.7.7",
    },
  });

  const healthyFile = join(projectRoot, ".codex", "skills", "mux-kimi", "SKILL.md");
  const healthyContent = await readFile(healthyFile, "utf8");

  assert.match(stdout, new RegExp(`code-mux forget ${staleEntry.entryId}`));
  assert.match(stdout, new RegExp(`code-mux relink ${staleEntry.entryId} /new/path`));
  assert.match(healthyContent, /Generated by `code-mux` v7\.7\.7/);

  await runInstalledCli(entryPath, ["forget", staleEntry.entryId], {
    cwd: projectRoot,
    env: { HOME: fakeHome },
  });

  const registryAfter = await readRegistry(fakeHome);
  assert.equal(registryAfter.entries.some((entry) => entry.entryId === staleEntry.entryId), false);
});

test("relink preserves entry id and lets the next update succeed on the new path", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const { projectRoot, entryPath } = await createLocalInstalledCli();
  const npmStub = await createNpmStub();
  const oldTarget = await makeTempDir("code-mux-old-target-");
  const newTarget = await makeTempDir("code-mux-new-target-");

  await runInstalledCli(entryPath, [
    "init",
    "--ai",
    "codex",
    "--ada",
    "qoder",
    "--target",
    oldTarget,
  ], {
    cwd: projectRoot,
    env: { HOME: fakeHome },
  });

  const registryBefore = await readRegistry(fakeHome);
  const entry = registryBefore.entries.find((candidate) => candidate.targetRoot === oldTarget);
  assert.ok(entry);

  await rm(oldTarget, { recursive: true, force: true });
  await runInstalledCli(entryPath, ["relink", entry.entryId, newTarget], {
    cwd: projectRoot,
    env: { HOME: fakeHome },
  });

  const registryAfterRelink = await readRegistry(fakeHome);
  const relinkedEntry = registryAfterRelink.entries.find((candidate) => candidate.entryId === entry.entryId);
  assert.ok(relinkedEntry);
  assert.equal(relinkedEntry.targetRoot, newTarget);

  await runInstalledCli(entryPath, ["update"], {
    cwd: projectRoot,
    env: {
      HOME: fakeHome,
      CODE_MUX_NPM_BIN: npmStub,
      CODE_MUX_TEST_NEW_VERSION: "6.6.6",
    },
  });

  const generatedFile = join(newTarget, ".codex", "skills", "mux-qoder", "SKILL.md");
  const content = await readFile(generatedFile, "utf8");
  assert.match(content, /Generated by `code-mux` v6\.6\.6/);
});

test("global relink refreshes the stored target root instead of the current HOME", async () => {
  const fakeHome = await makeTempDir("code-mux-home-");
  const newGlobalRoot = await makeTempDir("code-mux-new-home-");
  const workspace = await makeTempDir("code-mux-work-");
  const { entryPath } = await createGlobalInstalledCli();
  const npmStub = await createNpmStub();

  await runInstalledCli(entryPath, ["init", "--ai", "codex", "--ada", "kimi", "--global"], {
    cwd: workspace,
    env: { HOME: fakeHome },
  });

  const registryBefore = await readRegistry(fakeHome);
  const entry = registryBefore.entries[0];

  await runInstalledCli(entryPath, ["relink", entry.entryId, newGlobalRoot], {
    cwd: workspace,
    env: { HOME: fakeHome },
  });

  await runInstalledCli(entryPath, ["update"], {
    cwd: workspace,
    env: {
      HOME: fakeHome,
      CODE_MUX_NPM_BIN: npmStub,
      CODE_MUX_TEST_NEW_VERSION: "4.4.4",
    },
  });

  const content = await readFile(join(newGlobalRoot, ".codex", "skills", "mux-kimi", "SKILL.md"), "utf8");
  assert.match(content, /Generated by `code-mux` v4\.4\.4/);
});

test("transient _npx-style install paths are rejected", async () => {
  const parent = await makeTempDir("code-mux-parent-");
  const transientRoot = join(parent, "_npx", "workspace");
  await mkdir(transientRoot, { recursive: true });
  const { projectRoot, entryPath } = await createLocalInstalledCli(transientRoot);

  await assert.rejects(
    runInstalledCli(entryPath, ["update"], {
      cwd: projectRoot,
      env: { HOME: await makeTempDir("code-mux-home-") },
    }),
    /transient package-manager caches/i,
  );
});
