import { join } from "node:path";
import { readFile } from "node:fs/promises";
import { cleanupSandbox, createSandbox, createSandboxEnv } from "./lib/sandbox-env.mjs";

const sandbox = await createSandbox("code-mux-smoke-run-");

try {
  process.env.HOME = sandbox.home;
  process.env.CODE_MUX_TEST_HOME = sandbox.home;
  process.env.CODE_MUX_TEST_ROOT = sandbox.testRoot;

  const {
    createGlobalInstalledCli,
    createLocalInstalledCli,
    createNpmStub,
    makeTempDir,
    runInstalledCli,
  } = await import("../tests/test-helpers.mjs");

  const local = await createLocalInstalledCli();
  const globalCli = await createGlobalInstalledCli();
  const npmStub = await createNpmStub();
  const workspace = await makeTempDir("code-mux-smoke-work-");

  await runInstalledCli(local.entryPath, ["init", "--ai", "codex", "--ada", "kimi"], {
    cwd: local.projectRoot,
  });
  await runInstalledCli(globalCli.entryPath, ["init", "--ai", "claude", "--artifact", "command", "--ada", "qoder", "--global"], {
    cwd: workspace,
  });

  const updateResult = await runInstalledCli(local.entryPath, ["update"], {
    cwd: local.projectRoot,
    env: createSandboxEnv(sandbox, {
      CODE_MUX_NPM_BIN: npmStub,
      CODE_MUX_TEST_NEW_VERSION: "5.5.5",
    }),
  });

  const localOutput = await readFile(join(local.projectRoot, ".codex", "skills", "mux-kimi", "SKILL.md"), "utf8");
  const globalOutput = await readFile(join(sandbox.home, ".claude", "commands", "code-mux", "qoder.md"), "utf8");
  const summary = {
    localInit: /Host: `codex`/.test(localOutput),
    globalInit: /Host: `claude`/.test(globalOutput),
    updatePhase: /phase\trefresh/.test(updateResult.stdout),
    updatedVersion: /Generated by `code-mux` v5\.5\.5/.test(localOutput) && /Generated by `code-mux` v5\.5\.5/.test(globalOutput),
  };

  if (Object.values(summary).includes(false)) {
    throw new Error(`Smoke verification failed: ${JSON.stringify(summary)}`);
  }

  console.log(JSON.stringify(summary, null, 2));
} finally {
  await cleanupSandbox(sandbox);
}
